apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP
  ports:
    - name: nginx-port
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: crater

---

apiVersion: v1
kind: Service
metadata:
  name: crater-db-service
spec:
  type: ClusterIP
  ports:
    - name: db-port
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: crater